config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :user_interested_countries
  resources :study_languages
  resources :native_languages
  resources :profiles
  resources :learning_levels
  resources :countries
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :posts
  resources :demandes, path: "demande" do
    member do
      get "1truc", as: :_1truc, action: :_1truc
    end
  end
  resources :languages
  root 'welcome#index'
  get "demande", to: "welcome#demande"
  get "search", to: "welcome#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/demande.rb
class Demande < ApplicationRecord
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  before_action :set_demande, only: %i[ show edit update destroy _1truc]
  before_action :authenticate_user!, only: [:_1truc]

  # GET /demandes or /demandes.json
  def _1truc
    @post=Post.new(demande_id: @demande.id)
    render "posts/new"
  end
  def index
    @demandes = Demande.all
  end

  # GET /demandes/1 or /demandes/1.json
  def show
  end

  # GET /demandes/new
  def new
    @demande = Demande.new
  end

  # GET /demandes/1/edit
  def edit
  end

  # POST /demandes or /demandes.json
  def create
    @demande = Demande.new(demande_params)

    respond_to do |format|
      if @demande.save
        format.html { redirect_to demande_url(@demande), notice: "Demande was successfully created." }
        format.json { render :show, status: :created, location: @demande }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demandes/1 or /demandes/1.json
  def update
    respond_to do |format|
      if @demande.update(demande_params)
        format.html { redirect_to demande_url(@demande), notice: "Demande was successfully updated." }
        format.json { render :show, status: :ok, location: @demande }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @demande.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demandes/1 or /demandes/1.json
  def destroy
    @demande.destroy!

    respond_to do |format|
      format.html { redirect_to demandes_url, notice: "Demande was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demande
      @demande = Demande.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def demande_params
      params.require(:demande).permit(:name, :image, :icon)
    end
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/views/demandes/_demande.html.erb
<div id="<%= dom_id demande %>">
  <div><span style="color:white;background:<%= demande.icon %>;" class="myicon">
    <%= demande.image.html_safe %></span>
          <span class="name1">
    <%= demande.name %>
              </span>
                </div>

</div>

app/views/demandes/_form.html.erb
<%= form_with(model: demande) do |form| %>
  <% if demande.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(demande.errors.count, "error") %> prohibited this demande from being saved:</h2>

      <ul>
        <% demande.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, onkeydown:"name1.innerHTML=this.value;" %>
  </div>

  <div><span style="color:white;" id="myicon"></span>
      <span id="name1">
  </span>
  </div>


  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image,onkeydown:"myicon.innerHTML=this.value;" %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    de quelle couleur?
    <%= form.color_field :icon,onchange:"myicon.style.background=this.value;" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demandes/edit.html.erb
<h1>Editing demande</h1>

<%= render "form", demande: @demande %>

<br>

<div>
  <%= link_to "Show this demande", @demande %> |
  <%= link_to "Back to demandes", demandes_path %>
</div>

app/views/demandes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Demandes</h1>

<div id="demandes">
  <% @demandes.each do |demande| %>
    <%= render demande %>
    <p>
      <%= link_to "Show this demande", demande %>
    </p>
  <% end %>
</div>

<%= link_to "New demande", new_demande_path %>

app/views/demandes/new.html.erb
<h1>New demande</h1>

<%= render "form", demande: @demande %>

<br>

<div>
  <%= link_to "Back to demandes", demandes_path %>
</div>

app/views/demandes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @demande %>

<div>
  <%= link_to "Edit this demande", edit_demande_path(@demande) %> |
  <%= link_to "Back to demandes", demandes_path %>

  <%= button_to "Destroy this demande", @demande, method: :delete %>
</div>